<a href="https://colab.research.google.com/github/anshumanpanda711/python_pytorch/blob/main/PT2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

# Regular Python Lists:

In [6]:
array = [1,2,3,4,5]
array

[1, 2, 3, 4, 5]

In [7]:
twoDarray = [[1,2,3,4], [1,2,3,4], [1,2,3,4]]
twoDarray

[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]

# Numpy Arrays:


In [9]:
np1 = np.random.rand(3,4)
np1

array([[0.57207428, 0.14904409, 0.70530431, 0.75410378],
       [0.33949421, 0.89932803, 0.13365289, 0.60203533],
       [0.43427265, 0.72715716, 0.79951947, 0.00487373]])

# PyTorch Tensors

In [10]:
tensor2D = torch.randn(3,4)
tensor2D

tensor([[ 1.3397,  0.5049,  0.0990, -1.1795],
        [ 0.9687, -0.7206,  0.4239, -0.2470],
        [ 0.0367,  0.9692,  0.1865, -1.6122]])

In [11]:
myTensor = torch.tensor([[1,2,3],[1,2,3]])
myTensor

tensor([[1, 2, 3],
        [1, 2, 3]])

In [13]:
tensor3D = torch.zeros(2,3,4)
tensor3D

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])