<a href="https://colab.research.google.com/github/anshumanpanda711/python_pytorch/blob/main/PT3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

In [4]:
myTensor = torch.arange(10)
myTensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Reshape and View will be used:

## Tensor Operations:

# Using Reshape:

In [6]:
reshapedTensor = myTensor.reshape(2,5)
reshapedTensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

What if we don't know the input length?

---

We can use -1:








In [16]:
from numpy import random

randomInt = random.randint(1,13)
randomInt

10

In [17]:
torchint = torch.arange(randomInt)
torchint

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
torchint2 = torchint.reshape(2,-1)
torchint2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])



---



# Using View:

In [19]:
torch3 = torch.arange(16)
torch3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
torch4 = torch3.view(4,4)
torch4

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])



---

# These update from the original variable:

In [26]:
torch6 = torch.arange(10)
torch6

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
torch7 = torch6.reshape(2,5)
torch7

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [29]:
torch6[1] = 1234
torch6[1]

tensor(1234)

In [30]:
torch7

tensor([[   0, 1234,    2,    3,    4],
        [   5,    6,    7,    8,    9]])



---



## Using Slices:

In [31]:
torch8 = torch.arange(15)
torch8

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
torch9 = torch8.reshape(5,3)
torch9

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [34]:
torch9[:,2]

tensor([ 2,  5,  8, 11, 14])

In [35]:
torch9[3,:] # a certain column, or vector

tensor([ 9, 10, 11])

How to keep structure?


---


Use a colon at the back:

In [58]:
torch9[:,1:2]

tensor([[ 1],
        [ 4],
        [ 7],
        [10],
        [13]])

In [63]:
torch9[3:,:] # colon after the index results in the 3x1 vectors after and including the index

tensor([[ 9, 10, 11],
        [12, 13, 14]])

In [64]:
torch9[:3,:] # colon before the index results in the 3x1 vectors before the index

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])