<a href="https://colab.research.google.com/github/anshumanpanda711/python_pytorch/blob/main/PT4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Using Math Operations:

In [2]:
import torch
import numpy as np

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

# Addition:

In [4]:
tensor_a + tensor_b # Shorthand method

tensor([ 6,  8, 10, 12])

In [5]:
torch.add(tensor_a, tensor_b) # Longhand method

tensor([ 6,  8, 10, 12])

# Subtraction

In [6]:
tensor_b - tensor_a # Shorthand method

tensor([4, 4, 4, 4])

In [7]:
torch.sub(tensor_b, tensor_a) # Longhand method

tensor([4, 4, 4, 4])

# Multiplication

In [8]:
tensor_a * tensor_b # Shorthand method

tensor([ 5, 12, 21, 32])

In [9]:
torch.mul(tensor_a, tensor_b) # Longhand method

tensor([ 5, 12, 21, 32])

# Division

In [10]:
tensor_b / tensor_a # Shorthand method

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
torch.div(tensor_b, tensor_a) # Longhand method

tensor([5.0000, 3.0000, 2.3333, 2.0000])



---

## Further Operations:
# Modulus (Remainder):

In [12]:
tensor_b % tensor_a # Shorthand method

tensor([0, 0, 1, 0])

In [13]:
torch.remainder(tensor_b,tensor_a) # Longhand method

tensor([0, 0, 1, 0])

# Exponentiation:

In [14]:
tensor_a ** tensor_b # Shorthand method

tensor([    1,    64,  2187, 65536])

In [15]:
torch.pow(tensor_a, tensor_b) # Longhand method

tensor([    1,    64,  2187, 65536])



---

Another way to write longhand functions:

In [16]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

You can also reassign longhand using an underscore before the brackets:

In [17]:
tensor_a

tensor([1, 2, 3, 4])

In [18]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [19]:
tensor_a

tensor([ 6,  8, 10, 12])